### ISSUE TITLE
New version isn't available as an output

### ISSUE THREAD

**Issue by crqra** [commitizen-tools/commitizen-action#12]
Currently the newly created version is only available in the (undocumented) [`REVISION` env variable](https://github.com/commitizen-tools/commitizen-action/blob/master/entrypoint.sh#L44).

Having the version as an environment variable is useful in simple cases but if you're using `commitizen-action` multiple times (i.e. different workspaces) or have any other step that sets that env var, it gets overwritten.

It can be more useful if the new version is available as an [output](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter) of the step (i.e.: `version`), so it could be used like this:

```yaml
- id: cz
  uses: commitizen-tools/commitizen-action@master
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
     
- run: |
    echo "The new version is ${{ steps.cz.outputs.version }}"
```

Additionally, I don't think the `REVISION` env variable should be removed for backwards compatibility, but should be documented in the README, so it's easier for new people to know about it without having to look at the source code.

Any thoughts?
