### ISSUE TITLE
Incorrect Changelog behaviour?

### ISSUE THREAD

**Issue by PsypherPunk** [commitizen-tools/commitizen-action#22]
I'm hoping to clarify the configuration/behaviour for the `changelog` parameter. Based on the README (where the default is listed as `true`) I'd assumed `false` would disable it. That appears not to be the case…?

I'm using `commitizen-action` and have set `changelog` to `false`:

```yaml
      - uses: commitizen-tools/commitizen-action@master
        name: commitizen
        with:
          commitizen_version: v2.20.5
          changelog: false
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
```

However, this ended up creating a `CHANGELOG.md` file. Looking at the output, I can see that it's somehow inferring the `--changelog` flag:

```txt
Commitizen version:
2.20.5
Configuring git user and email...
Git name: github-actions[bot]
Git email: github-actions[bot]@users.noreply.github.com
Running cz:    --changelog
bump: version 0.2.0 → 0.2.1
tag to create: 0.2.1
increment detected: PATCH
```

However, after changing the `changelog` value to `""` (i.e. an empty string) instead of `false`, it behaves as expected as doesn't create the `CHANGELOG.md` file (and the above output simply lists `Running cz:`.)

Have I misinterpreted how the `changelog` value is supposed to be set?
