### ISSUE TITLE
[Bug] Semver rules & current branch

### ISSUE THREAD

**Issue by XeroxDev** [commitizen-tools/commitizen-action#24]
Hey! I noticed two bugs while setting up this action and testing it.

- [ ] 1. The action fails while pushing due to `fatal: couldn't find remote ref master`
- [ ] 2. Pre-Release generates invalid/wrong semver version

1. I've the following step
```yml
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md
          prerelease: ${{ steps.is_main.outputs.prerelease_type }}
```
and everything works expect the pushing. This is because the action tries to push to `master`, but I'm using `main`. Sadly I can't hard-code it, because I'm listening to multiple branches (for pre-release branches)

2. While testing I've noticed it generates for a (beta) pre-release the following version `1.1.0b0` but it should be `1.1.0-beta(.0)` instead (see [semver rules](https://semver.org/))
In their example for which version is lower and higher, they have the following Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

I hope it's okay, that I've not split this issue in two, that's why I've created checkboxes.
