### ISSUE TITLE
Using commitizen-action with an older version of commitizen (v2.23.0) results in a failure

### ISSUE THREAD

**Issue by churmuzache** [commitizen-tools/commitizen-action#40]
When I use the ```commitizen-action```, it fails with a ```cz: error: invalid choice: '21' (choose from 'init', 'commit', 'c', 'ls', 'example', 'info', 'schema', 'bump', 'changelog', 'ch', 'check', 'version')``` for commitizen v2.23.0.

Github actions config
```
      - name: Create bump and changelog
        id: cz
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          branch: ${{ github.ref }}
          commitizen_version: v2.23.0
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
```

I also use a git pre-commit hook that looks like this

```
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.23.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
```

The pre-commit check works as expected but when the code runs in GA, it fails with the above error. I've also attached a screenshot
![Screenshot 2022-07-05 at 13 00 08](https://user-images.githubusercontent.com/101735939/177322605-89ea3189-51d6-4ff6-9f92-fc669f9f7e02.png)
