### ISSUE TITLE
`check_consistency` has no effect

### ISSUE THREAD

**Issue by obrus-corcentric** [commitizen-tools/commitizen-action#53]
Hello, new option `check_consistency` has no any effect and command still called with `--check-consistency` option

Example of github action call:

```yaml
      - id: cz
        name: Bump version and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: false
          push: false
          merge: false
          check_consistency: false
```

`cz` command call was:

```bash
cz --no-raise 21 bump --yes --changelog --check-consistency
```
