### ISSUE TITLE
Clarification on how the workflow updates changelog and version

### ISSUE THREAD

**Issue by mfisco** [commitizen-tools/commitizen-action#54]
Hi,

I've been trying to integrate the action into my project for a couple of days now and can't seem to get it to work. I've attached the workflow file below but if anyone could shed some light on what I'm missing it would be greatly appreciated. For context, here is the scenario:

</br>

1. I create a new branch called `wip/something-cool` from  the`master` branch which is currently at _**v3.37.1**_.
2. On the `wip/something-cool` branch I create these three _"commits"_:
    - refactor: changed something to be cool
    - fix: made cool even more cool
    - docs: updates on cool stuff
3. I create a PR that runs a few status checks and after they all pass, I squash and merge the commits from`wip/something-cool` into `master`.
4. The `commitizen-action` workflow is triggered via the **push** event on the master branch.

</br>

At this point, I was expecting the action to use the commits from `wip/something-cool` to amend the changelog and bump the version from v3.37.1 to v3.37.2. Instead, the workflow says there aren't any commits to bump:

```sh
cz --no-raise 21 bump --yes --changelog --check-consistency --changelog-to-stdout >body.md
bump: version 3.37.1 → 3.37.1
tag to create: v3.37.1

[NO_COMMITS_TO_BUMP]
The commits found are not eligible to be bumped
Repository: xDev-LLC/Dropship
Actor: msf-dev
Not pushing
Done.
```

I tried it again with a different PR but this time changing the merged branch name to something like `fix: something cool` which **does** bump the version; however, in the changelog, you only have the `fix: something cool` and lose the squashed commits information. 

---

```yml
# .github/workflows/bumpversion.yml
name: Bump version 

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          fetch-depth: 0

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@0.15.1
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          changelog_increment_filename: body.md
```
