### ISSUE TITLE
Bump failing after upgrade from 0.16.0 -> 0.16.1

### ISSUE THREAD

**Issue by victorbadenas** [commitizen-tools/commitizen-action#58]
After release 0.16.1 with the fix for git safe directories was added, the base image's python version was bumped as well and was not reflected in the changelog.

When using custom-made packages inside of the docker image, this version can cause breakage in pipelines.

Is making the python version of the action configurable a desireable feature?

**Comment by woile** [comment]
Can you explain a bit more what are you using this action dockerfile for? Could you show an example? As of now I wouldn't recommend using the docker image of this action

**Comment by victorbadenas** [comment]
Thanks @woile for the quick reply! I'm not using the Docker directly but rather through the action. Basically having a:

```
    - uses: commitizen-tools/commitizen-action@0.16.1
      with:
        extra_requirements: my_package
        no_raise: ''
        github_token: <my_token>
```

where `my_package` is a custom package which contains an inheritance of `commitizen.cz.base.BaseCommitizen` with some custom functionalities. If any of the functionalities in the `extra_requirements` packages are incompatible with the python version, it makes this tool unusable for its purpose. In this regard, the previous version, which was using python 3.8 had the same issue, but it was not apparent to me.

NOTE: I cannot roll-back either as 0.16.0 does not have the safe directories fix.
