### ISSUE TITLE
options --name to select the commitizen

### ISSUE THREAD

**Issue by metya** [commitizen-tools/commitizen-action#62]
Options --name in action variables to select the commitizen, to use when bumping version.

**Comment by woile** [comment]
This can be achieved by configuring the `.cz.toml` 

```toml
[tool.commitizen]
name = "cz_conventional_commits"
```

And if you have a custom cz rule you'll have to add `extra_requirements` to the yaml:

```yaml
- id: cz
  name: Create bump and changelog
  uses: commitizen-tools/commitizen-action@master
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    extra_requirements: 'cz-emoji'
```

Is there another reason why you need this flag?
