### ISSUE TITLE
Bump commit in detached HEAD state not being pushed to master branch

### ISSUE THREAD

**Issue by jserpapinto** [commitizen-tools/commitizen-action#77]
Hey there!

I have this action:
```
    - id: cz
      name: Create bump and changelog
      if: steps.tag-check.outputs.exists == 'false'
      uses: commitizen-tools/commitizen-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        push: true
        changelog: true
        commit: true
        branch: master
        no_raise: 21
```

I was expecting that the `branch` config would push it into the master branch.

But the commit is in "detached HEAD state", for what I understand.

Can anyone enlighten me?

Thanks!
