### ISSUE TITLE
Add `working-directory` argument

### ISSUE THREAD

**Issue by evetion** [commitizen-tools/commitizen-action#8]
So we can run this action in a different subdirectory in case of larger/mono repositories:

```yaml
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          working-directory: backend  <--
```
