### ISSUE TITLE
Add a previous_version output, equivalent to the PREVIOUS_REVISION environment variable, or similar

### ISSUE THREAD

**Issue by Clockwork-Muse** [commitizen-tools/commitizen-action#93]
I'm trying to condition following steps in my workflow to only run if a bump occurred.  To that end, it would be nice if there was an output available, so I could do something like the following:

```yaml
- name: Run check
     if: ${{ steps.bump.outputs.version }} != ${{steps.bump.outputs.previous_version }}
        run: |
          echo "whatever"
```

... and/or some boolean output I could refer to afterwards (but knowing the previous version is useful generally).

I'm aware of the `PREVIOUS_VERSION` environment variable, however it's not available for `if` checks there, and autocomplete in VSCode of course complains it doesn't exist.

**Comment by Clockwork-Muse** [comment]
Okay, it turns out that the environment variable is available there, the following works:
```yaml
- name: Run check
     if: steps.bump.outputs.version != env.PREVIOUS_REVISION
        run: |
          echo "whatever"
```
(I'm still figuring out some aspects of GitHub actions and their expressions)

....  VSCode does complain pretty loudly about the reference potentially not being available, though...
