### ISSUE TITLE
outputs.version is set only if commit is true

### ISSUE THREAD

**Issue by Clockwork-Muse** [commitizen-tools/commitizen-action#94]
I have a workflow where I'm relying solely on the git history for version updates (no file changes). 
You can turn off any file updates or other git changes by writing:
```
- id: bump
  name: Create bump
    uses: commitizen-tools/commitizen-action@master
    with:
      push: false
      commit: false
```

... and you get the expected output:
```
cz --no-raise 21 bump --yes --changelog --files-only
bump: version 0.0.0 → 0.1.0
tag to create: 0.1.0
increment detected: MINOR

Repository: someorg/somerepo
Actor: clockwork-muse
Not pushing
Done.
```
**Unfortunately**, this doesn't update `outputs.version`, leaving it at the previous version (`0.0.0`).  This means I have to set `commit: true`, which disturbs the in-runner git state, which slightly complicates creation of releases (although in all honesty I probably should have done that anyways...).

**Comment by woile** [comment]
Is that how you access `outputs.version`? Looking at the script, the version is inserted even with `push: false, commit:false`, so it should work.

**Comment by Clockwork-Muse** [comment]
With the following workflow:
```yaml
name: Version Bump
concurrency:
  group: bump

on:
  push:

jobs:
  bump:
    runs-on: ubuntu-latest
    env:
      CHANGELOG_INCREMENT_FILENAME: ${{ github.workspace }}/INCREMENT.md
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: bump
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          push: false
          commit: false
          changelog_increment_filename: ${{ env.CHANGELOG_INCREMENT_FILENAME }}

      - id: envprint
        name: Print Env
        run: |
          printenv
          echo "Step Output: ${{ steps.bump.outputs.version }}"

      - id: release
        name: Create release
        if: steps.bump.outputs.version != env.PREVIOUS_REVISION
        run: |
          echo "${{ steps.bump.outputs.version }}"
```
The job output shows the following environment variable/output (truncated for brevity):
```shell
PREVIOUS_REVISION=0.1.0
REVISION=0.1.0
Step Output: 0.1.0
```
Additionally, the `release` job is skipped.

The generated changelog _does_ show the bump, but none of the outputs reflect that:
```markdown
## 0.1.1 (2024-12-23)

### Fix

- **test**: check for bump update

## 0.1.0 (2024-12-09)
```
