### ISSUE TITLE
[feature] cz action to output commit sha

### ISSUE THREAD

**Issue by reinthal** [commitizen-tools/commitizen-action#98]
# Feature:

Commitizen gh action outputs the sha of the commit as an output to be used for downstream builds

```yaml
   steps:
      - uses: actions/checkout@v4
        with:
          ref: ${steps.cz.outputs.sha}
```

# Background

We want to display the current build to the user in the UI of an api we are making with fastapi. To do this, we use the version in the `pyproject.toml`. However, Github actions does not checkout the latest commit on checkout, only the commit that triggered the gh workflow. Thus, when we add the version information before building the container, the latest commit from commitizen action is not added to the checked out code that builds the container. To solve this, we can add the following to our workflow:

```yaml
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
```
according to this issue in gh checkout action https://github.com/actions/checkout/issues/439. However, this this is sub-optimal for larger codebase where someone could merge to main between the commitizen bump and the gh action checkout operation. This would result in subsequent build of the wrong codebase. Suggested solution is to output the sha in the commitizen action when a commit is made so the sha can be used for subsequent checkouts.

```yaml
   steps:
      - uses: actions/checkout@v4
        with:
          ref: ${steps.cz.outputs.sha}
```

**Comment by bearomorphism** [comment]
**Triage**: feature request — expose the bump commit's SHA as an output so downstream steps can `actions/checkout@v4` it. Out of scope for the bug/doc sweep I'm doing today; leaving for maintainer review.

Workaround in the meantime — read the SHA in a follow-up step:

```yaml
- id: cz
  uses: commitizen-tools/commitizen-action@master
  with: { github_token: ${{ secrets.GITHUB_TOKEN }} }
- id: sha
  run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
- uses: actions/checkout@v4
  with:
    ref: ${{ steps.sha.outputs.sha }}
```
